### ISSUE TITLE
Proxy Configuration when using Rest-API

### ISSUE THREAD

**Issue by ChristophKind** [joelgriffith/browserless#146]
Hello
Can anyone say me how to use a proxy when using the rest api ???

**Comment by joelgriffith** [comment]
Hey @ChristophKind: you can set the proxy via query-string parameters. There's some docs located here on the subject: https://docs.browserless.io/docs/chrome-flags.html#launching-with-a-proxy. Even though this is using the puppeteer integration, you can use the same flags on the REST API.

One caveat is that _authenticated_ proxies don't work in the REST API's because each proxy seems to treat auth differently. For that, you can use the /function API (use the same query parameters), and handle authentication there, more generally this is a call to this puppeteer method: https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-pageauthenticatecredentials). Please refer to your proxies docs on how to pass authentication via puppeteer.

Hopefully this answers your question, if not please feel free to comment back here. Going to close for now.

**Comment by Nisthar** [comment]
@joelgriffith is there a way to change proxy after launching an instance?
