### ISSUE TITLE
Browserless do not respect ignoreHTTPSErrors parameter

### ISSUE THREAD

**Issue by Alex0007** [joelgriffith/browserless#165]
Code:

![image](https://user-images.githubusercontent.com/1143226/57526573-30328400-7347-11e9-9fdb-4828f609ff43.png)

Logs:

![image](https://user-images.githubusercontent.com/1143226/57525704-d5982880-7344-11e9-85cf-e91ae22c4421.png)

Puppeteer version is latest (1.15)

It seems that parameter `ignoreHTTPSErrors` is ignored

**Comment by joelgriffith** [comment]
Sorry for the confusion here @Alex0007. The logs here are simply printing query-string options passed in (in this case the `ignoreHTTPSErrors` in the logs is reflective of a query-string parameter `?ignoreHTTPSErrors=false`. The main issue here is that we handle `ignoreHTTPSErrors` via both query-string parameters, and puppeteer handles that as well. We're only showing query-string options here, which might not be reflective of what puppeteer's doing.

https://github.com/GoogleChrome/puppeteer/blob/master/lib/NetworkManager.js#L59 is where puppeteer does the check, and even though our logs are saying not to ignoreHTTPSErrors, it actually is.

I'll see if there's a better way to handle this since it's jarring -- but rest assured it's working as it should.

**Comment by joelgriffith** [comment]
Also this log is accurate that we _are_ launching Chrome with `ignoreHTTPSerrors`, however when you connect remotely that value get's set by your _local_ puppeteer running. Unfortunately there's no great way to log this initial connection and the parameters therein since we don't MITM any requests.

**Comment by Alex0007** [comment]
> We're only showing query-string options here
yeah, you're right. Puppeteer handles it correctly when provided in `.connect()` call

Closing

**Comment by gajus** [comment]
This is really confusing. I took thought that `ignoreHTTPSErrors` is being ignored.

**Comment by joelgriffith** [comment]
Yeah, I think just logging the received parameters (query-string) might be better.

**Comment by fmoessle** [comment]
I was confused as well. This behavior should be definitely present in the docs :)
