### ISSUE TITLE
RFC: Multiple version of Chrome in one image

### ISSUE THREAD

**Issue by joelgriffith** [joelgriffith/browserless#39]
Wanted to reach out and gather thoughts on bundling the last 2-5 version of Chrome in single image vs maintaining numerous image's with the only difference being the Chrome version.

PROS
- Less docker and related built maintenance
- Easier to understand build tools
- Quick way to test different versions for performance and other intricacies
- Can apply semver builds in docker (vs confusing `release-puppeteer-x.x.x`)

CONS
- Bigger image bundles
- Slightly more complex runtime (have to specify the puppeteer version in the URL or something similar).
- Having to download several version of Chrome, and building relevant tooling for each in the debugger (all the tooltip stuffs).
- Things like pre-booting Chrome become harder since you'd have to pre-boot one version only vs many.

Thoughts? Comments? Concerns?

**Comment by Filipoliko** [comment]
Hi, I am a little bit concerned about the size of the new image. I can imagine, that I would like to use 2 latest versions of chrome for some e2e testing, to check, that my website works for most of the users. But I dont see many reasons to check performance in multiple chrome versions, or any other use case. I am more afraid of the image size, since we are using your image inside CI, where it is not always cached and it would mean longer execution times, since each chrome is ~282Mb big (according to puppeteer readme). Also I dont see a need to have multiple release-puppeteer-x.x.x images merged in one, since probably most users will use one specific version of puppeteer and not multiple.

Maybe it would be good to write down some real use cases, which would be affected by this change.

Our scenarios:
- Image is running on the server to which we connect from our local computers to execute some tests - This change would not affect this scenario in any way
- Image is downloaded inside our CI, where it is used to execute some tests - This change may cause slow down of our pipelines

So from my perspective, it would be better to keep the things the way they are now, but I can understand, it can be time consuming to maintain more versions of the image. Thanks for your work!

**Comment by joelgriffith** [comment]
Been thinking some more about this, what if we made puppeteer a “runtime install”.  That way I’ll install whatever version you want on start (defaulting to latest), and it’s less maintenance overhead?

**Comment by Filipoliko** [comment]
If I understand it correctly, it would mean, that by running docker run, you would download the chrome for specified puppeteer version.. It would still cause extended execution time for our pipelines. Maybe we could take an inspiration from selenium grid.

![image](https://user-images.githubusercontent.com/755134/43704376-bc7c0066-995f-11e8-8ac9-63c0b06b0ca1.png)

You could have one docker image with server/hub (practically just this repository without any chrome downloaded) and then multiple docker images with different chrome versions. User would connect to the server and request a chrome instance with specified version, if a docker image with specified chrome version exists, it would create the chrome instance and the server would work as some sort of a bridge between the chrome node and user.

In this case, you would maintain only one docker image with the server. Other images with chrome installed should not need any maintenance. Users would just download the versions they need.

**Comment by jotajunior** [comment]
Since Puppeteer is so sensitive to Chrome versions, it seems very important to be able to define a version when launching browserless. Several use cases involve messing around with Chrome internals (e.g. saving userDataDir elsewhere), and across different versions it'd just break.

Being bundling different versions or selecting at runtime, this is generally a very good idea.

**Comment by joelgriffith** [comment]
Going to close this out as we’ll continue to do version-specific releases. I think I’ll give more thought on how to do this in a sane manner.
