### ISSUE TITLE
Browserless Debugger not fetching results

### ISSUE THREAD

**Issue by miles-collier** [joelgriffith/browserless#6]
I followed the Docker Quickstart:
1. `docker pull browserless/chrome`
2. `docker run --shm-size=1gb -p 3000:3000 browserless/chrome`
3. Visit `http://localhost:3000/` to use the interactive debugger.

I tried this on two separate VPS's, same issue - running Ubuntu Server 16.04.3 LTS.

It's up on one of my test systems: http://144.217.188.229:3000/

---

Edit: I've also tried the **Node Quickstart**, same issue.

**Comment by joelgriffith** [comment]
Yup, I see your issue:

```
inspector.js:3506 Mixed Content: The page at 'https://chrome-devtools-frontend.appspot.com/serve_file/@2abb5574c7b89c95ce7d295edc467a9edcab7769/inspector.html?ws=144.217.188.229:3000/devtools/page/2132EDB9AB8171814A48E8F0A210B2A8&remoteFrontend=true' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://144.217.188.229:3000/devtools/page/2132EDB9AB8171814A48E8F0A210B2A8'. This request has been blocked; this endpoint must be available over WSS.
```

The site/gateway _has_ to be under HTTPS in order for this to function properly. If you're running it on localhost it should work properly, otherwise you'll need it on a VPS that supports HTTPS.

There's a couple of other options as well if you're in a pinch:

- Use something like [localtunnel](https://github.com/localtunnel/localtunnel) to add https.
- If you have a domain name you can use [certbot to do HTTPS](https://certbot.eff.org/).

**Comment by miles-collier** [comment]
Perfect @joelgriffith! HTTPS is not a problem, put a domain on it and got certbox installed. All good to go, appreciated.

**Comment by joelgriffith** [comment]
Thanks for closing: I've added a "heads-up" in the readme to hopefully catch future issues!
