### ISSUE TITLE
Example for chromeless with Docker

### ISSUE THREAD

**Issue by stephanedebove** [joelgriffith/browserless#89]
Can you give an example as to how to run a chromeless script.js file with browserless? I'm using Docker, I'm able to build and run the browserless/chrome image but then what? Thanks!

**Comment by joelgriffith** [comment]
Appears chromeless is now deprecated in favor of puppeteer. You still can use it with browserless, however I’m not sure it’s worthwhile to do a fully-fledged page for it since it’s no longer being maintained.

That being said you should just need to specify the host and port of browserless when starting chromeless via: https://github.com/prisma/chromeless/blob/master/docs/api.md#chromeless-constructor-options. The interesting piece is the `cdp` options which can specify a remote connection
